### ISSUE TITLE
Sort MDC Keys

### ISSUE THREAD

**Issue by garth-gross** [inductiveautomation/kindling#138]
In the case where my log file has numerous values for a MDC key, the list that is presented is in the order the values appear in the logs.  This makes it very difficult to find a specific key when there are thousands of different potential values.  I would like to see the following:

1. The list being ordered by the items in the list
2. The ability to type in the specific value I am looking for

Problematic .idb file is attached as an example.  If I am attempting to find a specific OPC UA node address, it is a very frustrating experience.
![IssueScreenshot](https://github.com/inductiveautomation/kindling/assets/145372855/cd28e1cf-1519-42b7-8281-6dffe0bcd9c3)

[Ignition-QA-WIN10_Ignition_logs_20240229-1418.idb.zip](https://github.com/inductiveautomation/kindling/files/14454587/Ignition-QA-WIN10_Ignition_logs_20240229-1418.idb.zip)

**Comment by paul-griffith** [comment]
This fix is available now in 1.3.0
