### ISSUE TITLE
How can i decode the quarantined items

### ISSUE THREAD

**Issue by trisin** [inductiveautomation/kindling#144]
for the quarantined items, i want to know where and which script caused this. it is in .xml format, and i don't know how to decode it. Seems kindling doesn't support it. 
![image](https://github.com/inductiveautomation/kindling/assets/20191730/7f802feb-be4c-43ea-94da-1b5fa7b69af4)
![image](https://github.com/inductiveautomation/kindling/assets/20191730/1d8bbb13-70a2-4d82-a450-9315cce91448)
![image](https://github.com/inductiveautomation/kindling/assets/20191730/b61adc8e-726d-499d-94af-834273f69653)
![image](https://github.com/inductiveautomation/kindling/assets/20191730/adcc3fe0-1b07-4bb5-8804-fe54f0560831)

**Comment by trisin** [comment]
i find some info in the forum. so maybe the issue can be closed https://forum.inductiveautomation.com/t/base64-in-export-of-store-forward-quarantined-item/15656

**Comment by paul-griffith** [comment]
It's not perfect, but basic support for deserializing quarantine.xml files was added in 1.3.0: https://github.com/inductiveautomation/kindling/releases/tag/1.3.0
