### ISSUE TITLE
Improve log graph view "minimap"

### ISSUE THREAD

**Issue by paul-griffith** [inductiveautomation/kindling#17]
I think the core idea is solid, but the implementation is flawed. Take another stab at it, possibly from scratch.

**Comment by thirdgen88** [comment]
During leveraging of the tool yesterday (version 1.0.1, macOS, Intel), I noticed that the minimap (also labeled as "Display Density") doesn't seem to update with changes in the sorting order.  Might be something to put on a checklist if/when this feature is revisited.  Agreed on the core idea/concept being a good benefit! 👍
